// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtqONNhSihSrjwukP5ItSxBfH-hKpkbHQ',
    appId: '1:878641146406:web:5d2d2720aa9429cd8fd4e7',
    messagingSenderId: '878641146406',
    projectId: 'news-app-170c3',
    authDomain: 'news-app-170c3.firebaseapp.com',
    storageBucket: 'news-app-170c3.appspot.com',
    measurementId: 'G-M9KKTVXSGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAev6F2vuwjec0mRJkyTka0_MBpcZbcDJI',
    appId: '1:878641146406:android:6bba28335a67fc768fd4e7',
    messagingSenderId: '878641146406',
    projectId: 'news-app-170c3',
    storageBucket: 'news-app-170c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLXDhl421BkNB1bAAGRKeswAqrx_xAG50',
    appId: '1:878641146406:ios:b624f5a0504642bc8fd4e7',
    messagingSenderId: '878641146406',
    projectId: 'news-app-170c3',
    storageBucket: 'news-app-170c3.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLXDhl421BkNB1bAAGRKeswAqrx_xAG50',
    appId: '1:878641146406:ios:571b89f8a7319d8e8fd4e7',
    messagingSenderId: '878641146406',
    projectId: 'news-app-170c3',
    storageBucket: 'news-app-170c3.appspot.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
